networks:
  abiturient_net:
    name: abiturient_net

services:
  nginx:
    container_name: abiturient_nginx
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy_headers.conf:/etc/nginx/proxy_headers.conf
      - ./nginx/websocket_settings.conf:/etc/nginx/websocket_settings.conf
      - ./nginx/cors_headers.conf:/etc/nginx/cors_headers.conf
    depends_on:
      - abiturient_about
    networks:
      - abiturient_net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s

  abiturient_about:
    container_name: abiturient_about
    build:
      context: .
      dockerfile: abiturient/apps/about/Dockerfile
    env_file:
      - .env
    expose:
      - "$ABITURIENT_PORT"
    networks:
      - abiturient_net
    volumes:
      - ./abiturient:/abiturient
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s

  abiturient_auth:
    container_name: abiturient_auth
    build:
      context: .
      dockerfile: abiturient/apps/auth/Dockerfile
    env_file:
      - .env
    expose:
      - "$ABITURIENT_PORT"
    networks:
      - abiturient_net
    volumes:
      - ./abiturient:/abiturient
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s