networks:
  abiturient_net:
    name: abiturient_net

services:
  postgres:
    container_name: abiturient_db
    hostname: postgresql
    image: "postgres:14.1-alpine"
    env_file:
      - .env
    ports:
      - "5455:5432"
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - abiturient_net
    environment:
      - LANG=C.UTF_8

  redis:
    container_name: abitueint_redis
    image: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - abiturient_net