networks:
  abiturient_net:
    name: abiturient_net

services:
  postgres:
    container_name: abiturient_db
    hostname: postgresql
    image: "postgres:14.1-alpine"
    env_file:
      - .env
    ports:
      - "5455:5432"
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - abiturient_net
    environment:
      - LANG=C.UTF_8

  redis:
    container_name: abiturient_redis
    image: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - abiturient_net


  worker:
    container_name: abiturient_taskiq_worker
    build:
      context: .
    command: taskiq worker abiturient.core.taskiq:broker abiturient.apps.ent.tasks --log-level DEBUG #--fs-discover
    volumes:
      - ./abiturient:/abiturient
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - abiturient_net
