networks:
  abiturient_net:
    name: abiturient_net

services:
  db:
    container_name: abiturient_db
    image: "postgres:14.1-alpine"
    env_file:
      - .env
    ports:
      - "5432:5432"
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - abiturient_net
    environment:
      - LANG=C.UTF_8
