"""Add RURAL_QUOTA to ConcursEnum

Revision ID: 12c1dccd4b72
Revises: b7af1f2e271c
Create Date: 2024-05-31 09:43:07.488727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c1dccd4b72'
down_revision: Union[str, None] = 'b7af1f2e271c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
