"""Made year statistics, university, specialization models

Revision ID: 26242d67d1b7
Revises: 511c7598a989
Create Date: 2024-05-31 05:32:00.694499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26242d67d1b7'
down_revision: Union[str, None] = '511c7598a989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization',
    sa.Column('title', sa.String(length=127), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialization_id'), 'specialization', ['id'], unique=True)
    op.create_table('university',
    sa.Column('code', sa.String(length=63), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_id'), 'university', ['id'], unique=True)
    op.create_table('university_specialization',
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('specialization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('university_id', 'specialization_id', 'id')
    )
    op.create_index(op.f('ix_university_specialization_id'), 'university_specialization', ['id'], unique=True)
    op.create_table('year_statistics',
    sa.Column('university_specialization_id', sa.UUID(), nullable=True),
    sa.Column('concurs_type', sa.Enum('COMMON', 'RURAL_QUOTA', name='concursenum'), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('students_amount', sa.Integer(), nullable=True),
    sa.Column('min_pass_score', sa.Integer(), nullable=True),
    sa.Column('max_pass_score', sa.Integer(), nullable=True),
    sa.Column('average_pass_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['university_specialization_id'], ['university_specialization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_year_statistics_id'), 'year_statistics', ['id'], unique=True)
    op.add_column('educational_program_review', sa.Column('text', sa.Text(), nullable=False))
    op.drop_index('ix_educational_program_review_id', table_name='educational_program_review')
    op.create_index(op.f('ix_educational_program_review_id'), 'educational_program_review', ['id'], unique=True)
    op.drop_index('ix_profile_id', table_name='profile')
    op.create_index(op.f('ix_profile_id'), 'profile', ['id'], unique=True)
    op.drop_index('ix_state_id', table_name='state')
    op.create_index(op.f('ix_state_id'), 'state', ['id'], unique=True)
    op.add_column('university_review', sa.Column('text', sa.Text(), nullable=False))
    op.drop_index('ix_university_review_id', table_name='university_review')
    op.create_index(op.f('ix_university_review_id'), 'university_review', ['id'], unique=True)
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_university_review_id'), table_name='university_review')
    op.create_index('ix_university_review_id', 'university_review', ['id'], unique=False)
    op.drop_column('university_review', 'text')
    op.drop_index(op.f('ix_state_id'), table_name='state')
    op.create_index('ix_state_id', 'state', ['id'], unique=False)
    op.drop_index(op.f('ix_profile_id'), table_name='profile')
    op.create_index('ix_profile_id', 'profile', ['id'], unique=False)
    op.drop_index(op.f('ix_educational_program_review_id'), table_name='educational_program_review')
    op.create_index('ix_educational_program_review_id', 'educational_program_review', ['id'], unique=False)
    op.drop_column('educational_program_review', 'text')
    op.drop_index(op.f('ix_year_statistics_id'), table_name='year_statistics')
    op.drop_table('year_statistics')
    op.drop_index(op.f('ix_university_specialization_id'), table_name='university_specialization')
    op.drop_table('university_specialization')
    op.drop_index(op.f('ix_university_id'), table_name='university')
    op.drop_table('university')
    op.drop_index(op.f('ix_specialization_id'), table_name='specialization')
    op.drop_table('specialization')
    # ### end Alembic commands ###
