"""Updated fields in university and specialization

Revision ID: 4eb3f0422f21
Revises: 26242d67d1b7
Create Date: 2024-05-31 07:53:26.002274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb3f0422f21'
down_revision: Union[str, None] = '26242d67d1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'specialization', ['title'])
    op.create_unique_constraint(None, 'university', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'university', type_='unique')
    op.drop_constraint(None, 'specialization', type_='unique')
    # ### end Alembic commands ###
