"""Added relationship to year statistic

Revision ID: b7af1f2e271c
Revises: 4eb3f0422f21
Create Date: 2024-05-31 09:25:45.161506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7af1f2e271c'
down_revision: Union[str, None] = '4eb3f0422f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
